---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mynginx
  labels:
    type: web
spec:
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: mynginx
      labels:
        type: web
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8888
...
