---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongo
  labels:
    author: naveen
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
      type: db
  template:
    metadata:
      name: mymongo
      labels:
        author: naveen
        type: db
    spec:
      containers:
        - name: mymongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: naveen
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: naveen
...
