---
apiVersion: v1
kind: Pod
metadata:
  name: myhttpd
  labels:
    author: naveen
    type: web
spec:
  containers:
    - name: myhttpd
      image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: slave2
              operator: In
              values:
                - naveen2
...
