---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypersistentvolume
  labels:
    author: naveen
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data
...

