---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypersistentvolumeclaim
  labels:
    author: naveen
spec:
  storageClassName: maunal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
...
