---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    author: naveen
    type: web
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8888
...
