---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  namespace: mynamespace
  labels:
    author: naveen
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8888
...
