--- 
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    author: naveen
    type: database
spec:
 containers:
  - name: mysqldb 
    image: mysql
    env:
     - name: MYSQL_ROOT_USERNAME
       value: naveen
     - name: MYSQL_ROOT_PASSWORD
       value: naveen
     - name: MYSQL_ROOT_DB
       value: db
...
