---
apiVersion: v1
kind: Pod
metadata:
  name: myredis
  labels:
    author: naveen
spec:
  containers:
    - name: myredis
      image: redis
      volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: mypersistentvolumeclaim1
...
