---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mydatabase
  labels:
    author: naveen
    type: database
spec:
  replicas: 3
  template:
    metadata:
      name: mypostgres
      labels:
        author: naveen
        type: mydb
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: naveen
            - name: POSTGRES_USER
              value: naveen
            - name: POSTGRES-DB
              value: mydb
...
