---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myhttpd
  labels:
    author: naveen
    type: proxy
spec:
  replicas: 3
  template:
    metadata:
      name: myhttpd
      labels:
        author: naveen
        type: proxy
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8888
...
