---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    author: naveen
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
      type: proxy
  template:
    metadata:
      name: mysql
      labels:
        author: naveen
        type: proxy
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_ROOT_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
...
