---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    author: naveen
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
      type: db
  template:
    metadata:
      name: mysql
      labels:
        author: naveen
        type: db
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_USERNAME
              value: naveen
            - name: MYSQL_ROOT_PASSWORD
              value: naveen
            - name: MYSQL_ROOT_DATABASE
              value: db
...

