---
apiVersion: v1
kind: Service
metadata:
  name: myclusterip
  labels:
    author: naveen
    type: service
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    author: naveen
    type: db
...

