---
apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  labels:
    author: naveen
    type: service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    author: naveen
    type: web
...

