---
apiVersion: v1
kind: Service
metadata:
  name: mynodeport
  labels:
    author: naveen
    type: service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30005
  selector:
    author: naveen
    type: ci-cd
...

