---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    author: naveen
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
  template:
    metadata:
      name: mysql
      labels:
        author: naveen
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_USERNAME
              value: naveen
            - name: MYSQL_ROOT_PASSWORD
              value: naveen
            - name: MYSQL_ROOT_DATABASE
              value: db
      tolerations:
        - key: slave2
          operator: Equal
          value: naveen2
          effect: NoSchedule
...
