---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    author: naveen
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      volumeMounts:
        - name: myvolume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: myvolume
      emptyDir: {}
...

