---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongodb
  labels:
    author: naveen
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
  template:
    metadata:
      name: mymongodb
      labels:
        author: naveen
    spec:
      containers:
        - name: mymongodb
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: naveen
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: naveen
          volumeMounts:
            - name: myvolume
              mountPath: /data/db
      volumes:
        - name: myvolume
          emptyDir: {}
...
