---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels:
    author: naveen
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    author: naveen
...
