---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app
    author: naveen
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
  template:
    metadata:
      name: result-app-pod
      labels:
        author: naveen
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
...
