---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app
    author: naveen
spec:
  replicas: 2
  selector:
    matchLabels:
      author: naveen
  template:
    metadata:
      name: voting-app-pod
      labels:
        author: naveen
    spec:
     containers:
       - name: voting-app
         image: dockersamples/examplevotingapp_vote
...
