---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app
    author: naveen
spec:
  replicas: 1
  selector:
    matchLabels:
      author: naveen
  template:
    metadata:
      name: worker-app-pod
      labels:
        author: naveen
    spec:
     containers:
       - name: worker-app
         image: dockersamples/examplevotingapp_worker
...
